# Generated by Django 4.2.7 on 2025-03-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_keyword_remove_author_name_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series_number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
