# Generated by Django 4.2.7 on 2025-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
