# Generated by Django 4.2.7 on 2025-03-06 09:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_file_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['name'], 'verbose_name': 'Ключевое слово', 'verbose_name_plural': 'Ключевые слова'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['title'], 'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.RemoveIndex(
            model_name='author',
            name='books_autho_last_na_7ca250_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_file_ha_17b6f4_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='title_idx',
            old_name='books_book_title_d3218d_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='lang_idx',
            old_name='books_book_lang_99ab96_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='last_scan',
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books.author', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_hash',
            field=models.CharField(max_length=64, unique=True, verbose_name='Хеш файла'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_path',
            field=models.CharField(max_length=1000, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='book',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.keyword', verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='book',
            name='lang',
            field=models.CharField(default='ru', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='book',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.series', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series_number',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер в серии'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Ключевое слово'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание серии'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Название серии'),
        ),
    ]
