# Generated by Django 4.2.7 on 2025-03-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_archive',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Путь к архиву'),
        ),
        migrations.AddField(
            model_name='book',
            name='file_in_archive',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Путь внутри архива'),
        ),
    ]
